name: minimal_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - matplotlib
  - scipy
  - torch
  - pip:
      - addict
      - attrs
      - blinker
      - certifi
      - charset-normalizer
      - click
      - configargparse
      - contourpy
      - cycler
      - dash
      - dash-core-components
      - dash-html-components
      - dash-table
      - fastjsonschema
      - filelock
      - flask
      - fonttools
      - fsspec
      - idna
      - importlib-metadata
      - importlib-resources
      - itsdangerous
      - jinja2
      - joblib
      - jsonschema
      - jsonschema-specifications
      - jupyter-core
      - kiwisolver
      - markupsafe
      - matplotlib
      - mpmath
      - narwhals
      - nbformat
      - nest-asyncio
      - networkx
      - numpy
      - open3d
      - packaging
      - pandas
      - pillow
      - pkgutil-resolve-name
      - platformdirs
      - plotly
      - pyparsing
      - pyquaternion
      - python-dateutil
      - pytz
      - pyyaml
      - referencing
      - requests
      - retrying
      - rpds-py
      - scikit-learn
      - scipy
      - six
      - sympy
      - threadpoolctl
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - traitlets
      - typing-extensions
      - tzdata
      - urllib3
      - werkzeug
      - zipp
